// User data
const userData = {
    login: "zobkazi",
    id: 105772384,
    node_id: "U_kgDOBk31YA",
    avatar_url: "https://avatars.githubusercontent.com/u/105772384?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zobkazi",
    html_url: "https://github.com/zobkazi",
    followers_url: "https://api.github.com/users/zobkazi/followers",
    following_url: "https://api.github.com/users/zobkazi/following{/other_user}",
    gists_url: "https://api.github.com/users/zobkazi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/zobkazi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zobkazi/subscriptions",
    organizations_url: "https://api.github.com/users/zobkazi/orgs",
    repos_url: "https://api.github.com/users/zobkazi/repos",
    events_url: "https://api.github.com/users/zobkazi/events{/privacy}",
    received_events_url: "https://api.github.com/users/zobkazi/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
    name: "Zobaidul Kazi",
    company: "KaziByte",
    blog: "https://zobkazi.github.io/",
    location: "Bangladesh",
    email: null,
    hireable: true,
    bio: "As a passionate Full Stack Developer with a deep expertise in building scalable web applications and tackling complex problems.",
    twitter_username: "zobaidulkazi",
    public_repos: 33,
    public_gists: 6,
    followers: 8,
    following: 113,
    created_at: "2022-05-18T06:19:02Z",
    updated_at: "2025-02-23T14:05:40Z",
  };

  
export default userData;